### ISSUE TITLE
Cannot Create WebEx meeting

### ISSUE THREAD

**Issue by sakhanej** [webex/sdk-component-adapter#130]
Premise:
- Trying to create a Single page React app
- used the components defined for Creating and Joining the meeting.
- Able to connect and authenticate with access token

Issue:
- when trying to get the meeting created, getting below errors:
```
index.js:1 Get Meeting error:  Error: Could not find meeting with ID "sakhanej@cisco.webex.com"

MeetingsSDKAdapter.js:587 Uncaught Error: Could not find meeting with ID "sakhanej@cisco.webex.com" to add audio control
```
and above continues for video, share, remote

On investigation of API, the /people API is returning nothing, while get meeting details does get the meeting details.
https://hydra-a.wbx2.com/v1/people?email=sakhanej%40cisco.webex.com

**Comment by lalli-flores** [comment]
@sakhanej, the meeting ID is not the same thing as the meeting destination. A user email is a destination, once you start a meeting, that will generate a meeting ID.
Without sharing how you're using the components, you need to use the [`useMeetingDestination()` hook](https://github.com/webex/components/blob/master/src/components/hooks/useMeetingDestination.js) what would give you that ID, or you can use [`withMeeting()` HOC](https://github.com/webex/components/blob/master/src/components/hoc/withMeeting.jsx)

**Comment by sakhanej** [comment]
I am seeing the error in the fetchMeeting() function in [SDKComponentAdapter.js](https://github.com/webex/sdk-component-adapter/blob/master/src/MeetingsSDKAdapter.js). while creating meeting, this function returns "undefined"

**Comment by lalli-flores** [comment]
`fetchMeeting()` is a private method. Developers are not meant to access any methods other than those [outlined on the interface](https://github.com/webex/component-adapter-interfaces/blob/master/src/MeetingsAdapter.js)
