### ISSUE TITLE
Error: getRoomActivities(ID) must be defined in RoomsAdapter

### ISSUE THREAD

**Issue by rsaulat** [webex/sdk-component-adapter#245]
Seems RoomsSDKAdapter is missing implementation of getRoomActivities(ID) from RoomsAdapter interface. Is this a miss or the functionality is intentionally left out for future implementation.

**Comment by lalli-flores** [comment]
@rsaulat, a `RoomsAdapter` implementation for the SDK has not been done yet, hence why you won't find it yet.
