### ISSUE TITLE
Video and audio control issue

### ISSUE THREAD

**Issue by suren179** [webex/sdk-component-adapter#68]
Hi,

I'm using WebexMeeting from @webex/components
If user disables video or audio before clicking on Join Meeting button, then these controls won't work after the user joins.
User himself will see that video is being shared or audio is un-muted but rest of the participants (joined using desktop application) can't see the video or hear him (both remain muted).

[sample-code.zip](https://github.com/webex/sdk-component-adapter/files/4938136/sample-code.zip)

**Comment by lalli-flores** [comment]
Hi @suren179,
Thank you for letting us know about the issues you're experiences, and providing sample code!
Do you mind placing that sample code in a Github repository and share the link instead? This way is easier to see your sample code for everyone.

Going back to the topic, the team is aware of some UI issue with muting and we are in the process of fixing it. Hopefully is the same issue you're experiencing and it's all resolved.

**Comment by suren179** [comment]
Thanks for quick reply.
Will push my code to a repo and link it here.

**Comment by lalli-flores** [comment]
@suren179, can you verify with the latest version of the adapter?
This issue could be fixed by https://github.com/webex/sdk-component-adapter/pull/70 in [version 1.21.2](https://github.com/webex/sdk-component-adapter/blob/master/CHANGELOG.md#1212-2020-07-21).

**Comment by suren179** [comment]
Verified, fixed in [Version 1.21.1](https://github.com/webex/sdk-component-adapter/blob/master/CHANGELOG.md#1212-2020-07-21)
Thank you, @lalli-flores.

Fixed by PR [#70 ](url). Thank you, @jdaly13
